<a href="https://colab.research.google.com/github/na0706/20200826/blob/master/learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import sys
sys.path.append('/content/drive/My Drive/summer01')

import ic_module as ic

# 関数実行
ic.Learning(tsnum=30, nb_epoch=50, batch_size=8, learn_schedule=0.9)

>> 学習サンプル数 :  (252, 32, 32, 3)
>> 学習開始
Epoch 1/50
20/21 [===========================>..] - ETA: 0s - loss: 1.1037 - accuracy: 0.3625
Epoch 00001: val_loss improved from inf to 1.11275, saving model to best.hdf5
21/21 [==============================] - 2s 73ms/step - loss: 1.1030 - accuracy: 0.3665 - val_loss: 1.1127 - val_accuracy: 0.3297
Epoch 2/50
20/21 [===========================>..] - ETA: 0s - loss: 1.0941 - accuracy: 0.4187
Epoch 00002: val_loss improved from 1.11275 to 1.10004, saving model to best.hdf5
21/21 [==============================] - 1s 62ms/step - loss: 1.0941 - accuracy: 0.4161 - val_loss: 1.1000 - val_accuracy: 0.2747
Epoch 3/50
20/21 [===========================>..] - ETA: 0s - loss: 1.0382 - accuracy: 0.4938
Epoch 00003: val_loss improved from 1.10004 to 1.09724, saving model to best.hdf5
21/21 [==============================] - 1s 62ms/step - loss: 1.0369 - accuracy: 0.4969 - val_loss: 1.0972 - val_accuracy: 0.3846
Epoch 4/50
20/21 [===========================>.

In [18]:
import ic_module as ic
import os.path as op

while True:
    while True:
        imgname = input("\n>> 入力したい画像ファイル(「END」で終了) ： ")
        if op.isfile(imgname) or imgname == "END":
            break
        print(">> そのファイルは存在しません！")
    if imgname == "END":
        break

    # 関数実行
    ic.TestProcess(imgname)


>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/summer01/original01/test/000001 (1).jpg
1
2
3
>> 計算結果↓
[[3.4973482e-04 9.9942708e-01 2.2332484e-04]]
>> この画像は「kubota」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/summer01/original01/test/000002 (2).jpg
1
2
3
>> 計算結果↓
[[2.8276158e-02 9.7172171e-01 2.2426618e-06]]
>> この画像は「kubota」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/summer01/original01/test/000001 (2).jpg
1
2
3
>> 計算結果↓
[[9.8499322e-01 1.4960469e-02 4.6279030e-05]]
>> この画像は「ishihara」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/summer01/original01/test/000001.jpg
1
2
3
>> 計算結果↓
[[4.5170152e-01 5.4829186e-01 6.6337584e-06]]
>> この画像は「kubota」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/summer01/original01/test/000002 (1).jpg
1
2
3
>> 計算結果↓
[[7.1413615e-03 9.9283206e-01 2.6453699e-05]]
>> この画像は「kubota」です。

>> 入力したい画像ファイル(「END」で終了) ： /content/drive/My Drive/summer01/original01/test/000002 (2).jpg
1
2
3
>> 計算結果↓
[[2.8276158e-02 9.7172171e-01 